-- MySQL Script generated by MySQL Workbench
-- нд, 20-тра-2018 18:11:16 +0300
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema calendar
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `calendar` ;

-- -----------------------------------------------------
-- Schema calendar
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `calendar` DEFAULT CHARACTER SET utf8 ;
USE `calendar` ;

-- -----------------------------------------------------
-- Table `calendar`.`Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `calendar`.`Users` ;

CREATE TABLE IF NOT EXISTS `calendar`.`Users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `userName` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `calendar`.`EventTypes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `calendar`.`EventTypes` ;

CREATE TABLE IF NOT EXISTS `calendar`.`EventTypes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `slug` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;

CREATE UNIQUE INDEX `name_UNIQUE` ON `calendar`.`EventTypes` (`name` ASC);

CREATE UNIQUE INDEX `slug_UNIQUE` ON `calendar`.`EventTypes` (`slug` ASC);


-- -----------------------------------------------------
-- Table `calendar`.`Events`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `calendar`.`Events` ;

CREATE TABLE IF NOT EXISTS `calendar`.`Events` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `imgUrl` VARCHAR(255) NULL,
  `dateStart` DATETIME NULL,
  `dateEnd` DATETIME NULL,
  `latlong` POINT NULL,
  `location` VARCHAR(255) NULL,
  `descr` TEXT NULL,
  `price` JSON NULL,
  `appDeadline` DATETIME NULL,
  `maxPlayers` INT NULL,
  `owner_id` INT NOT NULL,
  `eventType_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Games_Users`
    FOREIGN KEY (`owner_id`)
    REFERENCES `calendar`.`Users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Events_EventTypes1`
    FOREIGN KEY (`eventType_id`)
    REFERENCES `calendar`.`EventTypes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;

CREATE INDEX `fk_Games_Users_idx` ON `calendar`.`Events` (`owner_id` ASC);

CREATE INDEX `fk_Events_EventTypes1_idx` ON `calendar`.`Events` (`eventType_id` ASC);

CREATE UNIQUE INDEX `name_UNIQUE` ON `calendar`.`Events` (`name` ASC);


-- -----------------------------------------------------
-- Table `calendar`.`EventAdmins`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `calendar`.`EventAdmins` ;

CREATE TABLE IF NOT EXISTS `calendar`.`EventAdmins` (
  `idUsers` INT NOT NULL,
  `idEvents` INT NOT NULL,
  PRIMARY KEY (`idUsers`, `idEvents`),
  CONSTRAINT `fk_Users_has_Events_Users1`
    FOREIGN KEY (`idUsers`)
    REFERENCES `calendar`.`Users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Users_has_Events_Events1`
    FOREIGN KEY (`idEvents`)
    REFERENCES `calendar`.`Events` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;

CREATE INDEX `fk_Users_has_Events_Events1_idx` ON `calendar`.`EventAdmins` (`idEvents` ASC);

CREATE INDEX `fk_Users_has_Events_Users1_idx` ON `calendar`.`EventAdmins` (`idUsers` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
